/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author 62823
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jsepakbola = new javax.swing.JLabel();
        jvoli = new javax.swing.JLabel();
        jabout = new javax.swing.JLabel();
        jukm = new javax.swing.JLabel();
        jhome = new javax.swing.JLabel();
        jbadminton = new javax.swing.JLabel();
        jlogout = new javax.swing.JLabel();
        jbasket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sepakbolapanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDaftar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        volipanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jdaftar = new javax.swing.JButton();
        badmintonpanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        basketpanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ukmpanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\pcr3.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("“Empowers You to Global Competition”");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 360, 30);

        jsepakbola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jsepakbola.setForeground(new java.awt.Color(255, 255, 255));
        jsepakbola.setText("-Sepak Bola");
        jsepakbola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsepakbolaMouseClicked(evt);
            }
        });
        jPanel1.add(jsepakbola);
        jsepakbola.setBounds(100, 260, 120, 30);

        jvoli.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jvoli.setForeground(new java.awt.Color(255, 255, 255));
        jvoli.setText("-VOLI");
        jvoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jvoliMouseClicked(evt);
            }
        });
        jPanel1.add(jvoli);
        jvoli.setBounds(100, 300, 80, 30);

        jabout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jabout.setForeground(new java.awt.Color(255, 255, 255));
        jabout.setText("About");
        jabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jaboutMouseClicked(evt);
            }
        });
        jPanel1.add(jabout);
        jabout.setBounds(40, 440, 120, 30);

        jukm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jukm.setForeground(new java.awt.Color(255, 255, 255));
        jukm.setText("Unit Kegiatan Mahasiswa");
        jukm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jukmMouseClicked(evt);
            }
        });
        jPanel1.add(jukm);
        jukm.setBounds(40, 210, 230, 40);

        jhome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jhome.setForeground(new java.awt.Color(255, 255, 255));
        jhome.setText("Home");
        jhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhomeMouseClicked(evt);
            }
        });
        jPanel1.add(jhome);
        jhome.setBounds(40, 170, 70, 30);

        jbadminton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbadminton.setForeground(new java.awt.Color(255, 255, 255));
        jbadminton.setText("-Badminton");
        jbadminton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbadmintonMouseClicked(evt);
            }
        });
        jPanel1.add(jbadminton);
        jbadminton.setBounds(100, 340, 120, 30);

        jlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlogout.setForeground(new java.awt.Color(255, 255, 255));
        jlogout.setText("Logout");
        jlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogoutMouseClicked(evt);
            }
        });
        jPanel1.add(jlogout);
        jlogout.setBounds(40, 530, 120, 30);

        jbasket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbasket.setForeground(new java.awt.Color(255, 255, 255));
        jbasket.setText("-Basket");
        jbasket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbasketMouseClicked(evt);
            }
        });
        jPanel1.add(jbasket);
        jbasket.setBounds(100, 380, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Downloads\\nikola-johnny-mirkovic-2RsQPnIH3go-unsplash_11zon (1).jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 601);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        mainpanel.setBackground(new java.awt.Color(255, 255, 255));
        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Calon Anggota Baru");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Selamat Datang Di Aplikasi Penerimaan");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\jadi1.jpg")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Unit Kegiatan Mahasiswa");

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(64, 64, 64))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        mainpanel.add(homepanel, "card2");

        sepakbolapanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Sepak Bola");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Unit Kegiatan Mahasiswa");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\download (1).jpg")); // NOI18N

        jLabel17.setText("Tertarik untuk bergabung?");

        jDaftar.setText("Daftar");
        jDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDaftarActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("  Unit Kegiatan Mahasiswa (UKM) Sepakbola ini merupakan \nsalah satu unit kegiatan mahasiswa  yang berfungsi sebagai \ntempat penyaluran minat dan bakat mahasiswa dalam \nbidang olahraga khususnya sepakbola dan futsal. UKM Sepak\nBola dibentuk pada tanggal 1 April 2007. ");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout sepakbolapanelLayout = new javax.swing.GroupLayout(sepakbolapanel);
        sepakbolapanel.setLayout(sepakbolapanelLayout);
        sepakbolapanelLayout.setHorizontalGroup(
            sepakbolapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepakbolapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sepakbolapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sepakbolapanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepakbolapanelLayout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addGroup(sepakbolapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepakbolapanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(168, 168, 168))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sepakbolapanelLayout.createSequentialGroup()
                                .addGroup(sepakbolapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(88, 88, 88))))
                    .addGroup(sepakbolapanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDaftar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        sepakbolapanelLayout.setVerticalGroup(
            sepakbolapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sepakbolapanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(sepakbolapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jDaftar))
                .addGap(14, 14, 14))
        );

        mainpanel.add(sepakbolapanel, "card3");

        volipanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Unit Kegiatan Mahasiswa");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Voli");

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\download (2).jpg")); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("  UKM Volleyball melakukan latihan rutin setiap minggunya,\nsparing patner dengan perguruan tinggi lain dan kegiatan \nyang paling ditunggu oleh mahasiswa adalah PROLIGA PCR,\ndimana UKM Volleyball bekerja sama dengan mahasiswa \nPCR dan juga pihak-pihak sponsor dan bahkan bekerja sama\ndengan perguruan tinggi lain untuk menyelenggarakan \nkompetisi yang mereferensi ke Proliga Indonesia");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel21.setText("Tertarik untuk bergabung?");

        jdaftar.setText("Daftar");
        jdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout volipanelLayout = new javax.swing.GroupLayout(volipanel);
        volipanel.setLayout(volipanelLayout);
        volipanelLayout.setHorizontalGroup(
            volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volipanelLayout.createSequentialGroup()
                .addGroup(volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(volipanelLayout.createSequentialGroup()
                        .addGroup(volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(volipanelLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)))
                            .addGroup(volipanelLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel19)))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(volipanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volipanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jdaftar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        volipanelLayout.setVerticalGroup(
            volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volipanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(volipanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jdaftar))
                .addContainerGap())
        );

        mainpanel.add(volipanel, "card4");

        badmintonpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Unit Kegiatan Mahasiswa");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Badminton");

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\images (3).jpg")); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("   Di UKM ini kita melaksanakan latihan rutin setiap hari Minggu\ndari jam 14:00 WIB s/d selesai. Dalam latihan rutin itu sendiri \njuga dilakukan kegiatan-kegiatan menarik seperti Games,\nperlombaan antar anggota dan lain sebagainya. UKM Badminton \nini tidak hanya melakukan latihan rutin setiap Minggu namun \njuga melaksanakan Perlombaan antar Mahasiswa yg lainnya,\nseperti Internal Cup Badminton, PCR CUP Badminton. ");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel25.setText("Tertarik untuk bergabung?");

        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout badmintonpanelLayout = new javax.swing.GroupLayout(badmintonpanel);
        badmintonpanel.setLayout(badmintonpanelLayout);
        badmintonpanelLayout.setHorizontalGroup(
            badmintonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(badmintonpanelLayout.createSequentialGroup()
                .addGroup(badmintonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(badmintonpanelLayout.createSequentialGroup()
                        .addGroup(badmintonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(badmintonpanelLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel22))
                            .addGroup(badmintonpanelLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabel23))
                            .addGroup(badmintonpanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(badmintonpanelLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel24)))
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        badmintonpanelLayout.setVerticalGroup(
            badmintonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(badmintonpanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(badmintonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        mainpanel.add(badmintonpanel, "card5");

        basketpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Unit Kegiatan Mahasiswa");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("Basket");

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\download (3).jpg")); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Beberapa turnamen sering dilakukan oleh UKM Basket seperti \nmelakukan Turnamen Basketball yang diikuti oleh siswa/i \nSMA/SMK sederajat se-Pekanbaru. Turnamen ini disebut Inter \nHigh School Basketball Tournament (IHSBT).");
        jScrollPane3.setViewportView(jTextArea3);

        jLabel29.setText("Tertarik untuk bergabung?");

        jButton2.setText("Daftar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basketpanelLayout = new javax.swing.GroupLayout(basketpanel);
        basketpanel.setLayout(basketpanelLayout);
        basketpanelLayout.setHorizontalGroup(
            basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basketpanelLayout.createSequentialGroup()
                .addGroup(basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basketpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(basketpanelLayout.createSequentialGroup()
                        .addGroup(basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(basketpanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(basketpanelLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addGroup(basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel26)
                                        .addGroup(basketpanelLayout.createSequentialGroup()
                                            .addGap(98, 98, 98)
                                            .addComponent(jLabel27))))))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        basketpanelLayout.setVerticalGroup(
            basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basketpanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(basketpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        mainpanel.add(basketpanel, "card6");

        ukmpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setText("Unit Kegiatan Mahasiswa(UKM)");

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("  Unit Kegiatan Mahasiswa (UKM) adalah suatu lembaga \nkemahasiswaan tempat berkumpulnya para mahasiswa \nyang mempunyai kesamaan minat, kegemaran, kreativitas,\ndan orientasi aktivitas penyaluran kegiatan ekstrakurikuler \ndi dalam kampus.\n\nManfaat Mengikuti Unit Kegiatan Mahasiswa (UKM):\n1. Menambah wawasan\n2. Pengalaman berorganisasi\n3. Menambah relasi\n4. Mengisi waktu luang dengan kegiatan positif\n\nBeberapa Jenis UKM Yang ada:\n1. Sepak Bola\n2. Voli\n3. Badminton\n4. Basket\n");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout ukmpanelLayout = new javax.swing.GroupLayout(ukmpanel);
        ukmpanel.setLayout(ukmpanelLayout);
        ukmpanelLayout.setHorizontalGroup(
            ukmpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ukmpanelLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(75, 75, 75))
            .addGroup(ukmpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        ukmpanelLayout.setVerticalGroup(
            ukmpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ukmpanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        mainpanel.add(ukmpanel, "card7");

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 480, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhomeMouseClicked
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        
        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jhomeMouseClicked

    private void jukmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jukmMouseClicked
        // TODO add your handling code here:
         mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        
        mainpanel.add(ukmpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
        
    }//GEN-LAST:event_jukmMouseClicked

    private void jsepakbolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsepakbolaMouseClicked
        // TODO add your handling code here:
         mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        
        mainpanel.add(sepakbolapanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jsepakbolaMouseClicked

    private void jvoliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jvoliMouseClicked
        // TODO add your handling code here:
         mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        
        mainpanel.add(volipanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jvoliMouseClicked

    private void jbadmintonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbadmintonMouseClicked
        // TODO add your handling code here:
         mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        
        mainpanel.add(badmintonpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jbadmintonMouseClicked

    private void jbasketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbasketMouseClicked
        // TODO add your handling code here:
         mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        // add panel
        
        mainpanel.add(basketpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_jbasketMouseClicked

    private void jaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaboutMouseClicked
        // TODO add your handling code here:
        about n = new about();
        n.setVisible(true);
    }//GEN-LAST:event_jaboutMouseClicked

    private void jlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogoutMouseClicked
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"anda yakin akan keluar?","PERINGATAN",dialogBtn);
        
        if (dialogResult == 0){
            System.exit(0);
        }else{
            
        }
        
    }//GEN-LAST:event_jlogoutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        formdaftar daftar = new formdaftar();
        daftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDaftarActionPerformed
        // TODO add your handling code here:
        formdaftar daftar = new formdaftar();
        daftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jDaftarActionPerformed

    private void jdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdaftarActionPerformed
        // TODO add your handling code here:
        formdaftar daftar = new formdaftar();
        daftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jdaftarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        formdaftar daftar = new formdaftar();
        daftar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel badmintonpanel;
    private javax.swing.JPanel basketpanel;
    private javax.swing.JPanel homepanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jDaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JLabel jabout;
    private javax.swing.JLabel jbadminton;
    private javax.swing.JLabel jbasket;
    private javax.swing.JButton jdaftar;
    private javax.swing.JLabel jhome;
    private javax.swing.JLabel jlogout;
    private javax.swing.JLabel jsepakbola;
    private javax.swing.JLabel jukm;
    private javax.swing.JLabel jvoli;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel sepakbolapanel;
    private javax.swing.JPanel ukmpanel;
    private javax.swing.JPanel volipanel;
    // End of variables declaration//GEN-END:variables
}
