/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author 62823
 */
public class table_ukm extends javax.swing.JFrame {
    /**
     * Creates new form table_ukm
     */
    public table_ukm() {
        initComponents();
        TampilData();
        KosongForm();
    }
    public void KosongForm(){
        jTextNIM.setEditable(true);
        jTextnama.setText(null);
        jTextemail.setText(null);
        jComboBoxprodi.setSelectedItem(this);
        jComboBoxjk.setSelectedItem(this);
        jComboBoxukm.setSelectedItem(this);
    }
    
    private void TampilData() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("NIM");
        model.addColumn("nama");
        model.addColumn("email");
        model.addColumn("Prodi");
        model.addColumn("jk");
        model.addColumn("ukm");
        String cari = jTextcari.getText();
        

        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "SELECT * FROM daftar Where nama LIKE'%"+cari+"%'";
            java.sql.Connection conn = (Connection) koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{ no++,res.getString(1), 
                    res.getString(2), res.getString(3), res.getString(4)
                    , res.getString(5), res.getString(6)});
            }
            jTableukm.setModel(model);
        } catch (SQLException e) {
            System.out.println("ERROR" + e.getMessage());
        }
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableukm = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonedit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextemail = new javax.swing.JTextField();
        jTextNIM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxprodi = new javax.swing.JComboBox<>();
        jComboBoxjk = new javax.swing.JComboBox<>();
        jComboBoxukm = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableukm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTableukm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableukmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableukm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 570, 270));

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Table Daftar Calon Anggota Unit Kegiatan Mahasiswa(UKM)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 50));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        jButtonedit.setText("Edit");
        jButtonedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, -1, -1));

        jButton4.setText("Cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, -1));

        jTextcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcariActionPerformed(evt);
            }
        });
        getContentPane().add(jTextcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 260, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\close.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jButton5.setText("Cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        jTextnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 170, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jTextemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextemailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, -1));

        jTextNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNIMActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prodi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jComboBoxprodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih", "Teknik Informatia", "Tekni Listrik", "Teknik Mekatronika", "Akuntasi" }));
        getContentPane().add(jComboBoxprodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jComboBoxjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih", "Laki-Laki", "Prempuan" }));
        getContentPane().add(jComboBoxjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        jComboBoxukm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih", "Sepak Bola", "Voli", "Badminton", "Basket" }));
        getContentPane().add(jComboBoxukm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("UKM");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\62823\\Pictures\\project\\4.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextcariActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO daftar VALUES('"+jTextNIM.getText()+"',"
                    + "'"+jTextnama.getText()+"',"
                    + "'"+jTextemail.getText()+"',"
                    + "'"+jComboBoxprodi.getSelectedItem()+"',"
                    + "'"+ jComboBoxjk.getSelectedItem()+"',"
                    + "'"+jComboBoxukm.getSelectedItem()+"')";
            
            java.sql.Connection conn=(Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Tambah Data Baru Berhasil");
            TampilData();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableukmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableukmMouseClicked
        // TODO add your handling code here:
        jTextNIM.setEditable(false);
        
        int baris = jTableukm.rowAtPoint(evt.getPoint());
        String NIM = jTableukm.getValueAt(baris, 1).toString();
        jTextNIM.setText(NIM);
        
        String nama = jTableukm.getValueAt(baris, 2).toString();
        jTextnama.setText(nama);
        
        String email = jTableukm.getValueAt(baris, 3).toString();
        jTextemail.setText(email);
        
        String Prodi = jTableukm.getValueAt(baris, 4).toString();
        jComboBoxprodi.setSelectedItem(Prodi);
        
        String jk = jTableukm.getValueAt(baris, 5).toString();
        jComboBoxukm.setSelectedItem(jk);
        
        String ukm = jTableukm.getValueAt(baris, 6).toString();
        jComboBoxukm.setSelectedItem(ukm);
        
        
    }//GEN-LAST:event_jTableukmMouseClicked

    private void jButtoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE daftar SET NIM = '"+jTextNIM.getText()
                    + "', nama='" + jTextnama.getText()
                    + "', email='" + jTextemail.getText()
                    + "', Prodi='" + jComboBoxprodi.getSelectedItem()
                    + "', jk='" + jComboBoxjk.getSelectedItem()
                    + "', ukm='" + jComboBoxukm.getSelectedItem()
                    + "' where NIM='" + jTextNIM.getText() + "'";
            
            java.sql.Connection conn = (Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Update Data Berhasil");
            TampilData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses Edit data Gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtoneditActionPerformed

    private void jTextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnamaActionPerformed

    private void jTextemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextemailActionPerformed

    private void jTextNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNIMActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "delete from daftar where NIM = '"+jTextNIM.getText()+"'";
            
            java.sql.Connection conn = (Connection)koneksi.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            TampilData();
            KosongForm();
            
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("/cetak/cetak_ukm.jasper"), null, koneksi.getKoneksi());
        JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TampilData();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table_ukm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table_ukm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table_ukm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table_ukm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table_ukm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonedit;
    private javax.swing.JComboBox<String> jComboBoxjk;
    private javax.swing.JComboBox<String> jComboBoxprodi;
    private javax.swing.JComboBox<String> jComboBoxukm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableukm;
    private javax.swing.JTextField jTextNIM;
    private javax.swing.JTextField jTextcari;
    private javax.swing.JTextField jTextemail;
    private javax.swing.JTextField jTextnama;
    // End of variables declaration//GEN-END:variables
}
